documents/config/routes.rb
Rails.application.routes.draw do
  	resources :documents
  	devise_for :models	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

documents/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

documents/app/models/document.rb
class Document < ApplicationRecord
end

documents/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

documents/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

documents/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create, :destroy, :update, :index, :show, :new]
  before_action :authenticate_model!, only: [:new]

  # GET /documents
  # GET /documents.json
  def index
  	@documents = Document.paginate(:page => params[:page], per_page: 2)
  	render json: {status: 'SUCCESS', message:'Loaded documents', data:@documents}, status: :ok
  end
  
  # GET /documents/1
  # GET /documents/1.json
  def show
	@document = Document.find(params[:id])
	render json: {status: 'SUCCESS', message:'Loaded document', data:@document}, status: :ok
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

      if @document.save
        render json: {status: 'SUCCESS', message:'Document created', data:@document}, status: :ok
      else
        render json: {status: 'ERROR', message:'Document not created', data:@document.errors}, status: :unprocessable_entity
      end

  end
  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
  	@document = Document.find(params[:id])
      if @document.update_attributes(document_params)
        render json: {status: 'SUCCESS', message:'Document updated', data:@document}, status: :ok
      else
		render json: {status: 'ERROR', message:'Document not updated', data:@document.errors}, status: :unprocessable_entity
      end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
  	@document = Document.find(params[:id])
    unless @document.blank?
    	if @document.destroy
    		render json: {status: 'SUCCESS', message:'Document deleted', data:@document}, status: :ok
    	else 
    		render json: {status: 'ERROR', message:'Document was not deleted', data:@document}, status: :unprocessable_entity
    	end
    else 
   		render json: {status: 'ERROR', message:'No such document', data:@document}, status: :unprocessable_entity
    end
  end

  private
    def document_params
      params.require(:document).permit(:name, :description, :content)
    end
end

documents/app/helpers/application_helper.rb
module ApplicationHelper
end

documents/app/helpers/documents_helper.rb
module DocumentsHelper
end

documents/app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :document_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :document_description %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :document_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

documents/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

documents/app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<% if model_signed_in? %>
  <li>
    <%= link_to 'Log Out', destroy_model_session_path, method: :delete %> 
  </li>
<% else %>
  <li>
    <%= link_to 'Register', new_model_registration_path %> 
  </li>
<% end %>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= document.content %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= will_paginate @documents %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

documents/app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

documents/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<%= link_to 'Log Out', destroy_model_session_path, method: :delete %> |
<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

documents/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>